`ifndef ALU_TB__SV
`define ALU_TB__SV

  // Generated by tbengy. Created by Prasad Pandit.

  `timescale 1ns/1ps
  `include "uvm_macros.svh"

  module alu_tb;
    import alu_test_pkg::*;
    import uvm_pkg::*;

    logic clk;

    alu_intf intf(.clk(clk));

    alu DUT (
      .clk(clk),
      .we(intf.we),
      .addr(intf.addr),
      .wdata(intf.wdata),
      .rdata(intf.rdata)
    );

    initial begin
      clk = 0;
      forever begin
        #10 clk = ~clk;
      end
    end

    initial begin
      uvm_config_db #(virtual alu_intf)::set(null, "*", "vintf", intf);
      run_test();
    end
  endmodule

`endif

//End of alu_tb
