`ifndef CORE_RV32I_TB__SV
`define CORE_RV32I_TB__SV

  // Generated by tbengy. Created by Prasad Pandit.

  `timescale 1ns/1ps
  `include "uvm_macros.svh"

  module core_rv32i_tb;
    import core_rv32i_test_pkg::*;
    import uvm_pkg::*;

    logic clk;

    core_rv32i_intf intf(.clk(clk));

    core_rv32i DUT (
      .clk(clk),
      .we(intf.we),
      .addr(intf.addr),
      .wdata(intf.wdata),
      .rdata(intf.rdata)
    );

    initial begin
      clk = 0;
      forever begin
        #10 clk = ~clk;
      end
    end

    initial begin
      uvm_config_db #(virtual core_rv32i_intf)::set(null, "*", "vintf", intf);
      run_test();
    end
  endmodule

`endif

//End of core_rv32i_tb
